language: python

# This list should match the versions listed in setup.py
python:
- 3.5
- 3.6

os:
  - linux

before_install:
- sudo apt-get update -qq

install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
- source activate test-environment
- pip install -e .[tf]
- pip install -e .[dev]
- pip install -e .[ci]

script:
- pytest -v --cov=donkeycar donkeycar/tests

stages:
    - name: deploy
      if: branch = master


after_success:
- codecov
